apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forum
  template:
    metadata:
      labels:
        app: forum
    spec:
      containers:
        - name: forum
          image: regis/openedx-forum:ironwood
          ports:
            - containerPort: 4567
          imagePullPolicy: Always
